spring:
  data:
    mongodb:
      port: 0
    rest:
      base-path: /api
  application:
    name: react-spring-data-rest
  mustache:
    suffix: .hbs
management:
  context-path: /mgmt
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
